# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-09 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190817_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/images'),
        ),
    ]
